name: Fly Deploy
on:
  workflow_dispatch:
  push:
    branches:    
      - 'main'
    paths-ignore:
      - 'docs'
      - 'README.md'

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
jobs:
  deploy:
    name: Deploy app
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: superfly/flyctl-actions/setup-flyctl@master
      
      - name: Deploy to fly.io
        run: flyctl deploy --remote-only --build-target run
